export const FULL_NUTRIENTS_MAP = [
  {
    attr_id: 301,
    usda_tag: 'CA',
    name: 'Calcium, Ca',
    name_display: 'Calcium',
    unit: 'mg',
  },
  {
    attr_id: 205,
    usda_tag: 'CHOCDF',
    name: 'Carbohydrate, by difference',
    name_display: 'Carbohydrates',
    unit: 'g',
  },
  {
    attr_id: 601,
    usda_tag: 'CHOLE',
    name: 'Cholesterol',
    name_display: 'Cholesterol',
    unit: 'mg',
  },
  {
    attr_id: 208,
    usda_tag: 'ENERC_KCAL',
    name: 'Energy',
    name_display: 'Calories',
    unit: 'kcal',
  },
  {
    attr_id: 606,
    usda_tag: 'FASAT',
    name: 'Fatty acids, total saturated',
    name_display: 'Saturated Fat',
    unit: 'g',
  },
  {
    attr_id: 204,
    usda_tag: 'FAT',
    name: 'Total lipid (fat)',
    name_display: 'Total Fat',
    unit: 'g',
  },
  {
    attr_id: 605,
    usda_tag: 'FATRN',
    name: 'Fatty acids, total trans',
    name_display: 'Trans Fat',
    unit: 'g',
  },
  {
    attr_id: 303,
    usda_tag: 'FE',
    name: 'Iron, Fe',
    name_display: 'Iron',
    unit: 'mg',
  },
  {
    attr_id: 291,
    usda_tag: 'FIBTG',
    name: 'Fiber, total dietary',
    name_display: 'Dietary Fiber',
    unit: 'g',
  },
  {
    attr_id: 306,
    usda_tag: 'K',
    name: 'Potassium, K',
    name_display: 'Potassium',
    unit: 'mg',
  },
  {
    attr_id: 307,
    usda_tag: 'NA',
    name: 'Sodium, Na',
    name_display: 'Sodium',
    unit: 'mg',
  },
  {
    attr_id: 203,
    usda_tag: 'PROCNT',
    name: 'Protein',
    name_display: 'Protein',
    unit: 'g',
  },
  {
    attr_id: 269,
    usda_tag: 'SUGAR',
    name: 'Sugars, total',
    name_display: 'Sugar',
    unit: 'g',
  },
  {
    attr_id: 539,
    usda_tag: 'SUGAR_ADD',
    name: 'Sugars, added',
    name_display: 'Added Sugars',
    unit: 'g',
  },
  {
    attr_id: 324,
    usda_tag: 'VITD',
    name: 'Vitamin D',
    name_display: 'Vitamin D',
    unit: 'IU',
  },
] as const
